sudo: required

services:
  - docker

os:
- linux

env:
  global:
    - DOCKER_IMAGE_NAME="hugo"
    - K8S_DEPLOYMENT_NAME="hugo-app"
    - DOCKER_HUB_ORG="sepulsa"

before_script:
- mkdir ~/.aws
- cp credentials ~/.aws/
- curl -Lo aws-iam-authenticator https://github.com/kubernetes-sigs/aws-iam-authenticator/releases/download/v0.3.0/heptio-authenticator-aws_0.3.0_linux_amd64
- chmod +x aws-iam-authenticator
- sudo mv aws-iam-authenticator /usr/local/bin
- curl -Lo kubectl https://storage.googleapis.com/kubernetes-release/release/v1.10.0/bin/linux/amd64/kubectl && chmod +x kubectl && sudo mv kubectl /usr/local/bin/
- mkdir kube
- cp kubeconfig kube/
- docker pull smesch/hugo
- docker pull smesch/html-proofer
- docker pull smesch/kubectl
- docker login -u "${DOCKER_USERNAME}" -p "${DOCKER_PASSWORD}"

script:
- docker run -v ${TRAVIS_BUILD_DIR}:/hugo_root smesch/hugo hugo -s /hugo_root
- docker run -v ${TRAVIS_BUILD_DIR}/public:/public smesch/html-proofer htmlproofer /public --external_only --only-4xx

after_script:
- docker build -t ${DOCKER_HUB_ORG}/${DOCKER_IMAGE_NAME}:${TRAVIS_BUILD_ID} .
- docker push ${DOCKER_HUB_ORG}/${DOCKER_IMAGE_NAME}:${TRAVIS_BUILD_ID}
- docker tag ${DOCKER_HUB_ORG}/${DOCKER_IMAGE_NAME}:${TRAVIS_BUILD_ID} ${DOCKER_USERNAME}/${DOCKER_IMAGE_NAME}:latest
- docker push ${DOCKER_HUB_ORG}/${DOCKER_IMAGE_NAME}:latest
- sed -i -e 's|KUBE_CA_CERT|'"${KUBE_CA_CERT}"'|g' kubeconfig
- sed -i -e 's|KUBE_ENDPOINT|'"${KUBE_ENDPOINT}"'|g' kubeconfig
- kubectl --kubeconfig kubeconfig set image deployment/${K8S_DEPLOYMENT_NAME} ${K8S_DEPLOYMENT_NAME}=${DOCKER_HUB_ORG}/${DOCKER_IMAGE_NAME}:$TRAVIS_BUILD_ID
#- docker run -v ${TRAVIS_BUILD_DIR}:/kube smesch/kubectl kubectl --kubeconfig /kube/kubeconfig set image deployment/${K8S_DEPLOYMENT_NAME} ${K8S_DEPLOYMENT_NAME}=${DOCKER_HUB_ORG}/${DOCKER_IMAGE_NAME}:$TRAVIS_BUILD_ID
